# action.yml
name: 'FireClover Cloud Application Deployment'
description: 'FireClover Cloud Application Deployment'
branding:
  icon: 'aperture'
  color: 'orange'

inputs:
  dns-zone:
    description: 'The existing DNS Zone to create new records in'
    required: true
  subdomain:
    description: 'The new subdomain to create in the DNS Zone for the deployment'
    required: true
  fireclover-subscription:
    description: 'The FireClover Subscription'
    required: true
  aws-account-id:
    description: 'The aws account registered at FireClover on your FireClover subscription'
  azure-tenant-id:  
    description: 'The azure tenant registered at FireClover on your FireClover subscription'
  azure-subscription-id:  
    description: 'The azure subscription registered at FireClover on your FireClover subscription'
  fireclover-architecture-template:
    description: 'The cloud deployment template to use for deployment'
  folder-redirects:
    description: 'Will redirect urls ending in a folder path to folder/index.html. Do not use for React SPAs.'
  web-path:
    description: 'The folder of the static web to deploy. Static web will be available at <domain>/*'
  api-path:
    description: 'The folder of the api to deploy. API will be available at <domain>/api/*'
  scan-cdk:
    description: 'Use the AWS Sustainability scanner for the resulting CDK'
    default: false
  bootstrap:
    description: 'Run bootstrap for the account using CDK'
    default: false
    
runs:
  using: composite
  steps:
    - name: Checkout AWS CDK template
      if: ${{ inputs.aws-account-id }}
      run: |
        git clone https://github.com/fireclover/deploy-template-aws-${{ inputs.fireclover-architecture-template || 'spa-static-site' }}.git fc-aws-cdk
      shell: bash
        
    - name: Build CDK AWS template
      if: ${{ inputs.aws-account-id }}
      run: |  
        echo ${{ inputs.fireclover-architecture-template }}
        cd fc-aws-cdk
        npm i
        npm run build
        # left for future use #cp ${GITHUB_ACTION_PATH}/.config-files ~/
      shell: bash
      
    - name: Bootstrap AWS
      if: ${{ inputs.aws-account-id && !!inputs.bootstrap }}
      run: |  
        cd fc-aws-cdk
        npm run cdk bootstrap aws://${{ inputs.aws-account-id }}/us-east-1
      shell: bash
      
    - name: Synth AWS
      if: ${{ inputs.aws-account-id && !!inputs.scan-cdk }}
      run: |  
        cd fc-aws-cdk
        if [ -z "${{ inputs.api-path }}" ]
        then
            npm run cdk synth -- --require-approval never -c webPath="../${{ inputs.web-path || 'dist' }}" -c domain=${{ inputs.dns-zone }} -c subdomain=${{ inputs.subdomain }} -c accountId=${{ inputs.aws-account-id }}
        else
            npm run cdk synth -- --require-approval never -c apiPath="../${{ inputs.api-path }}" -c webPath="../${{ inputs.web-path || 'dist' }}" -c domain=${{ inputs.dns-zone }} -c subdomain=${{ inputs.subdomain }} -c accountId=${{ inputs.aws-account-id }}
        fi
      shell: bash

    # This never yields any results anyway
    - name: AWS Sustainability Scanner
      if: ${{ inputs.aws-account-id && !!inputs.scan-cdk }}
      uses: aws-actions/sustainability-scanner@v1
      continue-on-error: true
      with:
        file: 'fc-aws-cdk/cdk.out/*template.json'

    - name: Deploy AWS
      if: ${{ inputs.aws-account-id }}
      run: |  
        cd fc-aws-cdk
        if [ -z "${{ inputs.api-path }}" ]
        then
            npm run cdk deploy -- --require-approval never -c webPath="../${{ inputs.web-path || 'dist' }}" -c domain=${{ inputs.dns-zone }} -c subdomain=${{ inputs.subdomain }} -c accountId=${{ inputs.aws-account-id }}
        else
            npm run cdk deploy -- --require-approval never -c apiPath="../${{ inputs.api-path }}" -c webPath="../${{ inputs.web-path || 'dist' }}" -c domain=${{ inputs.dns-zone }} -c subdomain=${{ inputs.subdomain }} -c accountId=${{ inputs.aws-account-id }}
        fi
      shell: bash

    - name: Checkout Azure Bicep template
      if: ${{ inputs.azure-tenant }}
      run: |
        git clone https://github.com/fireclover/deploy-template-azure-${{ inputs.fireclover-architecture-template }}.git fc-azure-bicep
      shell: bash
        
outputs:
  sbom:
    value: ${{ steps.scan.outputs.sbom }}
    description: "Path to a JSON SBOM file for the scan"
  vulns:
    value: ${{ steps.scan.outputs.vulns }}
    description: "Path to a JSON results file for the vulnerability scan"
